name: zip_extractor
description: A tool to extract ZIP files to multiple destinations
version: 1.0.0
# author: "Manasseh"

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  path: ^1.8.3
  archive: ^4.0.7
  file_picker: ^10.1.7

dev_dependencies:
  test: ^1.22.0
  lints: ^3.0.0

executables:
  extractor:
