name: zip_extractor
description: A Dart CLI tool to extract multiple ZIP files.
version: 1.0.0

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  path: ^1.8.3
  archive: ^4.0.7

dev_dependencies:
  test: ^1.22.0
